### PR TITLE
Reference to the Endpoints Page

### PR DESCRIPTION
**Pull request by miguelcfsilva11**

### CODE REVIEW

**Comment by EduRibeiro00** [comment]
Great job! I just have a few comments to make:

If the Move Generation endpoint will be used to highlight squares on the board when the user picks a certain piece to move, I think the type of that piece and its position on the board will also need to be passed as an argument.

In the Update Board endpoint, I don't know if the order should be calculated in the client and passed to the server as an argument. It seems like something the server should take care of, and in order to do that it needs the `last_move` and `castling_chance`.

Maybe we can also think about the pros and cons of returning moves and positions in Coordinate Notation, or in coordinate pairs (x, y)?

**Comment by EduRibeiro00** [comment]
Also, you can say in the PR's description "closes #1", to automatically close the Issue when the PR is merged ;)

**Comment by miguelcfsilva11** [comment]
Thank you!

When it comes to the Move Generation function, I think I misunderstood how it should fulfill its purpose. I had in mind a different way to get those spots highlighted in the board: in a first instance, we would call the Move Generation function (let's call it MG from now on to keep things simple), and obtain all possible moves such as ("e2e4", "d2e4", "e2e5", "e2e6"), for example. Then, when the user touches a piece, we would use the square where that same piece stands ("e2", for example) to filter the spots to where that piece can move to. Using this same sample of moves, when moving the piece on "e2", only ("e2e4", "e2e5", "e2e6") would remain on the list of possible moves when playing that piece. Then, it would be easy to filter out the spots that matter to us from each single string, which would give us ("e4", "e5", "e6") and highlight those squares right away. Following this same approach, whenever the user would touch two or more pieces in a row, it would not be necessary to call MG once again, as we would only need to filter the important positions like we did in the example above. I'm not sure if that would be optimal when looking from the performance standpoint, so it is definitely something that we should think about and discuss in the future.

I think I was not very explicit on the Update Board Enpoint. My text was kind of fuzzy. The order will be calculated by the server, with the function call **check_order**, that takes as parameters the initial position of the piece, the square it was moved to and the color of the pieces that user is playing. After the order is computed by the server (note that it doesn't need `last_move` nor `castling_chance` to do so), another function is called to update the board (**make_move**). So everything is done by the server (please correct me if I'm wrong, I'm not that familiar with the client-side and server-side concepts ).

Last but not least, I've written a parser that takes strings in Coordinate Notation and converts them to coordinate pairs (x, y). That will be necessary for every single function. It is a really simple operation, embedded in the functioning of the Engine.

> Also, you can say in the PR's description "closes #1", to automatically close the Issue when the PR is merged ;)

(P.S: I did not know about this, I'll make sure to use it in the future ;)

**Comment by GambuzX** [comment]
Great wiki 👌 

There are multiple ways to implement the highlight part, the one you described looks good to me. We can just call the endpoint at the start of each round and use that information on the frontend until the user decides it's move.

**Pull request merged**
